manifest = "c991e4ba5e1e445f471a22cb90cacb53583254a56872aacd001a5186e5a709a5"

[[dependency]]
package = "github.com/buckaroo-pm/boost-hana"
target = "//:hana"

[[dependency]]
package = "github.com/buckaroo-pm/boost-preprocessor"
target = "//:preprocessor"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "fc4d65435c49b5b4fbbf0d4867ee8f69bfd42ef1"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "f2f2d0d85496b72eeff1186518deb7e23c757bfd"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "82480080750b32b3ef2e3f12157b5c556ae35c0d"

[lock."github.com/buckaroo-pm/boost-hana"]
versions = [ "branch=master" ]
revision = "ae0069cbb5e385d6976ef7caa9748a4e06143f46"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"
